# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cerebrio < Formula
  desc "Cerebrio CLI — agent-first knowledge platform interface"
  homepage "https://github.com/cerebrio-ai/cerebrio-cli"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cerebrio-ai/cerebrio-cli/releases/download/v0.1.1/cerebrio_0.1.1_darwin_amd64.tar.gz"
      sha256 "926d9735ecdad69165a3c04629069b2af275faaed682d3bc12ccacc0cde2e299"

      define_method(:install) do
        bin.install "cerebrio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cerebrio-ai/cerebrio-cli/releases/download/v0.1.1/cerebrio_0.1.1_darwin_arm64.tar.gz"
      sha256 "723c8478aed0865e407ae9f033df76de95cc2490451db8fc1e9dcfb395ee6362"

      define_method(:install) do
        bin.install "cerebrio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cerebrio-ai/cerebrio-cli/releases/download/v0.1.1/cerebrio_0.1.1_linux_amd64.tar.gz"
      sha256 "e140216d95057419e2f809ea8abcc6075e20e3597c3a1d04bd11af2d9992b0ec"
      define_method(:install) do
        bin.install "cerebrio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cerebrio-ai/cerebrio-cli/releases/download/v0.1.1/cerebrio_0.1.1_linux_arm64.tar.gz"
      sha256 "6d53fffee53fc26f6863c6bca29bd413805249e0b7d3dacbc63d9a4741ece856"
      define_method(:install) do
        bin.install "cerebrio"
      end
    end
  end

  test do
    system "#{bin}/cerebrio", "--version"
  end
end
