# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cerebrio < Formula
  desc "Cerebrio CLI — agent-first knowledge platform interface"
  homepage "https://github.com/cerebrio-ai/cerebrio-cli"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cerebrio-ai/cerebrio-cli/releases/download/v0.1.2/cerebrio_0.1.2_darwin_amd64.tar.gz"
      sha256 "6a0b8fb3314b7cb33b57452ac76d9f18ff3134ee77e32afca70ef4c8559eacb7"

      define_method(:install) do
        bin.install "cerebrio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cerebrio-ai/cerebrio-cli/releases/download/v0.1.2/cerebrio_0.1.2_darwin_arm64.tar.gz"
      sha256 "75e1c1ead83070a729f0a7536a5d7dd2ed2b93c1d91e6da3df79d331797cc56c"

      define_method(:install) do
        bin.install "cerebrio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cerebrio-ai/cerebrio-cli/releases/download/v0.1.2/cerebrio_0.1.2_linux_amd64.tar.gz"
      sha256 "d54df0d2668d7d8d60e6368afae8a39895d9321d8f8c11f5bfa9357c068d1376"
      define_method(:install) do
        bin.install "cerebrio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cerebrio-ai/cerebrio-cli/releases/download/v0.1.2/cerebrio_0.1.2_linux_arm64.tar.gz"
      sha256 "0c9f91dfb8d3b203f65baa342af1fbc1ed313d845249336ea78adf83900cec2e"
      define_method(:install) do
        bin.install "cerebrio"
      end
    end
  end

  test do
    system "#{bin}/cerebrio", "--version"
  end
end
